import {Card} from './card';

export const DECK: Card[] = [
  {value: 1, suit: 'Spades', face: '1', img: 'assets/imgs/cards/AS.png'},
  {value: 2, suit: 'Spades', face: '2', img: 'assets/imgs/cards/2S.png'},
  {value: 3, suit: 'Spades', face: '3', img: 'assets/imgs/cards/3S.png'},
  {value: 4, suit: 'Spades', face: '4', img: 'assets/imgs/cards/4S.png'},
  {value: 5, suit: 'Spades', face: '5', img: 'assets/imgs/cards/5S.png'},
  {value: 6, suit: 'Spades', face: '6', img: 'assets/imgs/cards/6S.png'},
  {value: 7, suit: 'Spades', face: '7', img: 'assets/imgs/cards/7S.png'},
  {value: 8, suit: 'Spades', face: '8', img: 'assets/imgs/cards/8S.png'},
  {value: 9, suit: 'Spades', face: '9', img: 'assets/imgs/cards/9S.png'},
  {value: 10, suit: 'Spades', face: '10', img: 'assets/imgs/cards/10S.png'},
  {value: 10, suit: 'Spades', face: 'J', img: 'assets/imgs/cards/JS.png'},
  {value: 10, suit: 'Spades', face: 'Q', img: 'assets/imgs/cards/QS.png'},
  {value: 10, suit: 'Spades', face: 'K', img: 'assets/imgs/cards/KS.png'},
  {value: 1, suit: 'Hearts', face: '1', img: 'assets/imgs/cards/AH.png'},
  {value: 2, suit: 'Hearts', face: '2', img: 'assets/imgs/cards/2H.png'},
  {value: 3, suit: 'Hearts', face: '3', img: 'assets/imgs/cards/3H.png'},
  {value: 4, suit: 'Hearts', face: '4', img: 'assets/imgs/cards/4H.png'},
  {value: 5, suit: 'Hearts', face: '5', img: 'assets/imgs/cards/5H.png'},
  {value: 6, suit: 'Hearts', face: '6', img: 'assets/imgs/cards/6H.png'},
  {value: 7, suit: 'Hearts', face: '7', img: 'assets/imgs/cards/7H.png'},
  {value: 8, suit: 'Hearts', face: '8', img: 'assets/imgs/cards/8H.png'},
  {value: 9, suit: 'Hearts', face: '9', img: 'assets/imgs/cards/9H.png'},
  {value: 10, suit: 'Hearts', face: '10', img: 'assets/imgs/cards/10H.png'},
  {value: 10, suit: 'Hearts', face: 'J', img: 'assets/imgs/cards/JH.png'},
  {value: 10, suit: 'Hearts', face: 'Q', img: 'assets/imgs/cards/QH.png'},
  {value: 10, suit: 'Hearts', face: 'K', img: 'assets/imgs/cards/KH.png'},
  {value: 1, suit: 'Diamonds', face: '1', img: 'assets/imgs/cards/AD.png'},
  {value: 2, suit: 'Diamonds', face: '2', img: 'assets/imgs/cards/2D.png'},
  {value: 3, suit: 'Diamonds', face: '3', img: 'assets/imgs/cards/3D.png'},
  {value: 4, suit: 'Diamonds', face: '4', img: 'assets/imgs/cards/4D.png'},
  {value: 5, suit: 'Diamonds', face: '5', img: 'assets/imgs/cards/5D.png'},
  {value: 6, suit: 'Diamonds', face: '6', img: 'assets/imgs/cards/6D.png'},
  {value: 7, suit: 'Diamonds', face: '7', img: 'assets/imgs/cards/7D.png'},
  {value: 8, suit: 'Diamonds', face: '8', img: 'assets/imgs/cards/8D.png'},
  {value: 9, suit: 'Diamonds', face: '9', img: 'assets/imgs/cards/9D.png'},
  {value: 10, suit: 'Diamonds', face: '10', img: 'assets/imgs/cards/10D.png'},
  {value: 10, suit: 'Diamonds', face: 'J', img: 'assets/imgs/cards/JD.png'},
  {value: 10, suit: 'Diamonds', face: 'Q', img: 'assets/imgs/cards/QD.png'},
  {value: 10, suit: 'Diamonds', face: 'K', img: 'assets/imgs/cards/KD.png'},
  {value: 1, suit: 'Clubs', face: '1', img: 'assets/imgs/cards/AC.png'},
  {value: 2, suit: 'Clubs', face: '2', img: 'assets/imgs/cards/2C.png'},
  {value: 3, suit: 'Clubs', face: '3', img: 'assets/imgs/cards/3C.png'},
  {value: 4, suit: 'Clubs', face: '4', img: 'assets/imgs/cards/4C.png'},
  {value: 5, suit: 'Clubs', face: '5', img: 'assets/imgs/cards/5C.png'},
  {value: 6, suit: 'Clubs', face: '6', img: 'assets/imgs/cards/6C.png'},
  {value: 7, suit: 'Clubs', face: '7', img: 'assets/imgs/cards/7C.png'},
  {value: 8, suit: 'Clubs', face: '8', img: 'assets/imgs/cards/8C.png'},
  {value: 9, suit: 'Clubs', face: '9', img: 'assets/imgs/cards/9C.png'},
  {value: 10, suit: 'Clubs', face: '10', img: 'assets/imgs/cards/10C.png'},
  {value: 10, suit: 'Clubs', face: 'J', img: 'assets/imgs/cards/JC.png'},
  {value: 10, suit: 'Clubs', face: 'Q', img: 'assets/imgs/cards/QC.png'},
  {value: 10, suit: 'Clubs', face: 'K', img: 'assets/imgs/cards/KC.png'},

];
